
CREATE TABLE CLIENTES (
    CODCLIENTE INT(6) PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    CPF VARCHAR(11),
    DT_NASC DATE,
    ENDERECO VARCHAR(100),
    TELEFONE VARCHAR(20)
);

CREATE TABLE PRODUTOS (
    CODPRODUTO INT(6) PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100),
    PRECO DOUBLE,
    QTDE INT,
    CATEGORIA VARCHAR(100)
);

CREATE TABLE USUARIOS (
    CODUSUARIO INT(6) PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    CPF VARCHAR(11),
    LOGIN VARCHAR(11),
    SENHA VARCHAR(100)
);

CREATE TABLE FORNECEDORES (
    CODFORNECEDOR INT(6) PRIMARY KEY AUTO_INCREMENT,
    CNPJ VARCHAR(20),
    ENDERECO VARCHAR(100),
    TELEFONE VARCHAR(20),
    RAZAOSOCIAL VARCHAR(100)
);

CREATE TABLE VENDAS (
    CODVENDA INT(6) PRIMARY KEY AUTO_INCREMENT,
    DTVENDA DATE,
    VALOR DOUBLE,
    CODPRODUTO INT(6),
    QTDVENDA VARCHAR(100)
);

CREATE TABLE FP (
    FK_FORNECEDORES_CODFORNECEDOR INT(6),
    FK_PRODUTOS_CODPRODUTO INT(6)
);

CREATE TABLE UV (
    FK_USUARIOS_CODUSUARIO INT(6),
    FK_VENDAS_CODVENDA INT(6)
);

CREATE TABLE CV (
    FK_CLIENTES_CODCLIENTE INT(6),
    FK_VENDAS_CODVENDA INT(6)
);

CREATE TABLE PV (
    FK_PRODUTOS_CODPRODUTO INT(6),
    FK_VENDAS_CODVENDA INT(6)
);
 
ALTER TABLE FP ADD CONSTRAINT FK_FP_1
    FOREIGN KEY (FK_FORNECEDORES_CODFORNECEDOR)
    REFERENCES FORNECEDORES (CODFORNECEDOR)
    ON DELETE SET NULL;
 
ALTER TABLE FP ADD CONSTRAINT FK_FP_2
    FOREIGN KEY (FK_PRODUTOS_CODPRODUTO)
    REFERENCES PRODUTOS (CODPRODUTO)
    ON DELETE SET NULL;
 
ALTER TABLE UV ADD CONSTRAINT FK_UV_1
    FOREIGN KEY (FK_USUARIOS_CODUSUARIO)
    REFERENCES USUARIOS (CODUSUARIO)
    ON DELETE RESTRICT;
 
ALTER TABLE UV ADD CONSTRAINT FK_UV_2
    FOREIGN KEY (FK_VENDAS_CODVENDA)
    REFERENCES VENDAS (CODVENDA)
    ON DELETE SET NULL;
 
ALTER TABLE CV ADD CONSTRAINT FK_CV_1
    FOREIGN KEY (FK_CLIENTES_CODCLIENTE)
    REFERENCES CLIENTES (CODCLIENTE)
    ON DELETE RESTRICT;
 
ALTER TABLE CV ADD CONSTRAINT FK_CV_2
    FOREIGN KEY (FK_VENDAS_CODVENDA)
    REFERENCES VENDAS (CODVENDA)
    ON DELETE SET NULL;
 
ALTER TABLE PV ADD CONSTRAINT FK_PV_1
    FOREIGN KEY (FK_PRODUTOS_CODPRODUTO)
    REFERENCES PRODUTOS (CODPRODUTO)
    ON DELETE SET NULL;
 
ALTER TABLE PV ADD CONSTRAINT FK_PV_2
    FOREIGN KEY (FK_VENDAS_CODVENDA)
    REFERENCES VENDAS (CODVENDA)
    ON DELETE SET NULL;